server:
  port: 8080
blog:
  api: http://127.0.0.1:${server.port}
  cms: http://127.0.0.1:8079
  name: AnQin Blog
  view: http://127.0.0.1:8081
comment:
  default-open: true
  notify:
    channel: mail
http:
  proxy:
    server:
      host: 127.0.0.1
      port: 7890
      timeout: 10000
logging:
  file: blog-api/log/blog-dev
  level:
    root: info
    top:
      aqlog: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: SpringBoot-ABlog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/anqin_blog?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
  data:
    elasticsearch:
      client:
        reactive:
          username: elastic
          password: 123456
          socket-timeout:

  # 数据库迁移配置
  flyway:
    #开启 flyway
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    # flyway.baseline-on-migrate设置为true表示在执行迁移时，如果数据库中没有记录迁移历史，则会自动执行基线迁移。
    baseline-on-migrate: true
    # 创建迁移脚本：在src/main/resources/db/migration目录下，创建SQL脚本文件，按照Flyway的命名规则命名。
    # 例如，可以创建一个名为 V1__create_table.sql的文件，其中包含创建表的SQL语句。
    # 启动应用程序：当您启动Spring Boot应用程序时，Flyway会自动检测并执行未应用的迁移脚本。它会根据脚本文件的版本号顺序依次执行。
    # Flyway会自动创建一个名为flyway_schema_history的表，用于记录已应用的迁移历史.
    locations: classpath:db/migration
    schema: anqin_blog

  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    password: XXXXXXX
    port: 25
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    username: 1306895785@qq.com
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 10000ms
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
tg:
  bot:
    api: https://api.telegram.org/bot
    chat-id: XXXX
    reverse-proxy-url: XXXXXX
    token: XXXXXXXX
    use-proxy: false
    use-reverse-proxy: true
token:
  expireTime: 259200000
  secretKey: XXXXXXX
upload:
  channel: aliyun
  file:
    access-path: /image/**
    path: /Users/aqlog/Desktop/upload/
    resources-locations: file:${upload.file.path}
  github:
    repos: addnns/blog-imags
    repos-path: /comment/avatar
    token: XXXXXXX
    username: addnns
  upyun:
    bucket-name: nblog
    domain: https://cdn.example.com
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
    path: /comment/avatar
    username: aqlog


# 用来储存用户评论qq头像
aliyun:
  oss:
    file:
      bucketname: XXX
      endpoint: XXX
      keyid: XXX
      keysecret: XXXXX
      path: XXXX




# 基于 grafana prometheus（普罗米修斯） 监控

# 1、将所有Spring Web 监控点暴露， 就可以对外提供各种的指标数据了
management:
  endpoints:
    web:
      exposure:
        include: "*"
  # end
  # 2、将 SpringWeb 暴露的数据转为 prometheus 格式
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always # 查看更多的细节
  # 3、将指标设置为 允许导出
  metrics:
    export:
      prometheus:
        enabled: true